Repository quantumlib/qsim, pull requests merged in 2020-10, with the labels that each got.

#200 Add release process pointer
  docs/release-qsimcirq.md
Labels: cla: yes

#201 Update usage.md
  docs/usage.md
Labels: cla: yes

#202 Use absolute links in README.
  README.md
Labels: cla: yes

#204 Adds zenodo config
  .zenodo.json
  README.md
Labels: cla: yes

#205 Add matrix routines for multi-qubit gates.
  docs/type_reference.md
  lib/BUILD
  lib/bits.h
  lib/fuser.h
  lib/gate.h
  lib/gate_appl.h
  lib/matrix.h
  tests/matrix_test.cc
Labels: cla: yes

#203 Add overview doc
  docs/overview.md
Labels: cla: yes, documentation

#206 bump cirq to 0.9.1
  requirements.txt
Labels: cla: yes

#207 Refactor statespace.
  apps/qsim_base.cc
  apps/qsim_von_neumann.cc
  lib/hybrid.h
  lib/run_qsim.h
  lib/statespace.h
  lib/statespace_avx.h
  lib/statespace_basic.h
  lib/statespace_sse.h
  lib/vectorspace.h
  pybind_interface/pybind_main.cpp
  tests/run_qsim_test.cc
  tests/simulator_testfixture.h
  tests/statespace_testfixture.h
Labels: cla: yes

#209 Refactor simulator.
  lib/hybrid.h
  lib/run_qsim.h
  lib/simulator_avx.h
  lib/simulator_basic.h
  lib/simulator_sse.h
  lib/vectorspace.h
  tests/simulator_testfixture.h
Labels: cla: yes

#210 Update Cirq gates.
  lib/gates_cirq.h
  tests/gates_cirq_testfixture.h
  tests/run_qsim_test.cc
  tests/run_qsimh_test.cc
Labels: cla: yes

#211 Fix integer parameters in qsimcirq.
  qsimcirq/qsim_circuit.py
Labels: cla: yes

#208 Fix link to parameterized gates docs.
  docs/cirq_interface.md
Labels: cla: yes

#212 Update version to 0.5.0
  setup.py
Labels: cla: yes

#214 Fix gates with nonzero global shift.
  qsimcirq/qsim_circuit.py
  qsimcirq_tests/qsimcirq_test.py
Labels: cla: yes

#213 Use latest Cirq version in qsim
  docs/cirq_interface.md
  docs/tutorials/qsimcirq.ipynb
  qsimcirq/qsim_simulator.py
  requirements.txt
Labels: cla: yes

#215 Update to version 0.5.1
  setup.py
Labels: cla: yes, kokoro:run

#216 Add initial support for multi-qubit and controlled gates.
  docs/input_format.md
  lib/circuit_qsim_parser.h
  lib/fuser.h
  lib/fuser_basic.h
  lib/gate.h
  lib/gate_appl.h
  lib/gates_cirq.h
  lib/gates_qsim.h
  lib/hybrid.h
  lib/simulator_avx.h
  lib/simulator_basic.h
  lib/simulator_sse.h
  lib/unitary_calculator_basic.h
  tests/circuit_qsim_parser_test.cc
  tests/fuser_basic_test.cc
  tests/gates_qsim_test.cc
  tests/simulator_testfixture.h
Labels: cla: yes

#218 Fix overlapping qubits.
  lib/circuit_qsim_parser.h
  tests/circuit_qsim_parser_test.cc
Labels: cla: yes

#219 Polish qsimcirq getting started guide.
  docs/tutorials/qsimcirq.ipynb
Labels: cla: yes

#221 Polish docs
  docs/cirq_interface.md
  docs/input_format.md
  docs/overview.md
  docs/release-qsimcirq.md
  docs/usage.md
Labels: cla: yes

#220 Remove COPY .git from Dockerfile
  Dockerfile
Labels: cla: yes

#222 Fix links in type reference
  docs/type_reference.md
Labels: cla: yes

#225 Add multi-qubit and multi-control gates.
  lib/gate.h
  lib/simulator_avx.h
  lib/simulator_basic.h
  lib/simulator_sse.h
  tests/BUILD
  tests/simulator_avx_test.cc
  tests/simulator_basic_test.cc
  tests/simulator_sse_test.cc
  tests/simulator_testfixture.h
Labels: cla: yes

#229 Update docs landing page.
  docs/_index.yaml
Labels: cla: yes

#231 Add functions to make controlled gates.
  lib/circuit_qsim_parser.h
  lib/gate.h
  tests/simulator_testfixture.h
Labels: cla: yes
